// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: sku.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SkuDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	SpgId    int32    `protobuf:"varint,3,opt,name=spg_id,json=spgId,proto3" json:"spg_id,omitempty"`
	Image    []string `protobuf:"bytes,4,rep,name=image,proto3" json:"image,omitempty"`
	Price    float32  `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Param    []string `protobuf:"bytes,6,rep,name=param,proto3" json:"param,omitempty"`
	Saleable bool     `protobuf:"varint,7,opt,name=saleable,proto3" json:"saleable,omitempty"`
	Valid    bool     `protobuf:"varint,8,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *SkuDetail) Reset() {
	*x = SkuDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sku_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkuDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuDetail) ProtoMessage() {}

func (x *SkuDetail) ProtoReflect() protoreflect.Message {
	mi := &file_sku_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuDetail.ProtoReflect.Descriptor instead.
func (*SkuDetail) Descriptor() ([]byte, []int) {
	return file_sku_proto_rawDescGZIP(), []int{0}
}

func (x *SkuDetail) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SkuDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SkuDetail) GetSpgId() int32 {
	if x != nil {
		return x.SpgId
	}
	return 0
}

func (x *SkuDetail) GetImage() []string {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *SkuDetail) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SkuDetail) GetParam() []string {
	if x != nil {
		return x.Param
	}
	return nil
}

func (x *SkuDetail) GetSaleable() bool {
	if x != nil {
		return x.Saleable
	}
	return false
}

func (x *SkuDetail) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type SkuDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Skus []*SkuDetail `protobuf:"bytes,1,rep,name=skus,proto3" json:"skus,omitempty"`
}

func (x *SkuDetails) Reset() {
	*x = SkuDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sku_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkuDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuDetails) ProtoMessage() {}

func (x *SkuDetails) ProtoReflect() protoreflect.Message {
	mi := &file_sku_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuDetails.ProtoReflect.Descriptor instead.
func (*SkuDetails) Descriptor() ([]byte, []int) {
	return file_sku_proto_rawDescGZIP(), []int{1}
}

func (x *SkuDetails) GetSkus() []*SkuDetail {
	if x != nil {
		return x.Skus
	}
	return nil
}

type CreateSku struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title    string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	SpgId    int32    `protobuf:"varint,2,opt,name=spg_id,json=spgId,proto3" json:"spg_id,omitempty"`
	Image    []string `protobuf:"bytes,3,rep,name=image,proto3" json:"image,omitempty"`
	Price    float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Param    string   `protobuf:"bytes,5,opt,name=param,proto3" json:"param,omitempty"`
	Salebale bool     `protobuf:"varint,6,opt,name=salebale,proto3" json:"salebale,omitempty"`
	Valid    bool     `protobuf:"varint,7,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *CreateSku) Reset() {
	*x = CreateSku{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sku_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSku) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSku) ProtoMessage() {}

func (x *CreateSku) ProtoReflect() protoreflect.Message {
	mi := &file_sku_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSku.ProtoReflect.Descriptor instead.
func (*CreateSku) Descriptor() ([]byte, []int) {
	return file_sku_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSku) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSku) GetSpgId() int32 {
	if x != nil {
		return x.SpgId
	}
	return 0
}

func (x *CreateSku) GetImage() []string {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *CreateSku) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateSku) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

func (x *CreateSku) GetSalebale() bool {
	if x != nil {
		return x.Salebale
	}
	return false
}

func (x *CreateSku) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_sku_proto protoreflect.FileDescriptor

var file_sku_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x6b, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbc, 0x01, 0x0a, 0x09, 0x53, 0x6b, 0x75,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x15, 0x0a, 0x06,
	0x73, 0x70, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x70,
	0x67, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x61, 0x6c, 0x65, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x61, 0x6c, 0x65, 0x61, 0x62, 0x6c,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x2c, 0x0a, 0x0a, 0x53, 0x6b, 0x75, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1e, 0x0a, 0x04, 0x73, 0x6b, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x53, 0x6b, 0x75, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52,
	0x04, 0x73, 0x6b, 0x75, 0x73, 0x22, 0xac, 0x01, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x6b, 0x75, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x70, 0x67,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x70, 0x67, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x61, 0x6c, 0x65, 0x62, 0x61, 0x6c, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x61, 0x6c, 0x65, 0x62, 0x61, 0x6c, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x32, 0x69, 0x0a, 0x06, 0x53, 0x6b, 0x75, 0x53, 0x72, 0x76, 0x12, 0x2f,
	0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x0b, 0x2e, 0x53, 0x6b, 0x75, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x00, 0x12,
	0x2e, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x0a, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x6b, 0x75, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42,
	0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_sku_proto_rawDescOnce sync.Once
	file_sku_proto_rawDescData = file_sku_proto_rawDesc
)

func file_sku_proto_rawDescGZIP() []byte {
	file_sku_proto_rawDescOnce.Do(func() {
		file_sku_proto_rawDescData = protoimpl.X.CompressGZIP(file_sku_proto_rawDescData)
	})
	return file_sku_proto_rawDescData
}

var file_sku_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sku_proto_goTypes = []interface{}{
	(*SkuDetail)(nil),     // 0: SkuDetail
	(*SkuDetails)(nil),    // 1: SkuDetails
	(*CreateSku)(nil),     // 2: CreateSku
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_sku_proto_depIdxs = []int32{
	0, // 0: SkuDetails.skus:type_name -> SkuDetail
	3, // 1: SkuSrv.GetAll:input_type -> google.protobuf.Empty
	2, // 2: SkuSrv.Create:input_type -> CreateSku
	1, // 3: SkuSrv.GetAll:output_type -> SkuDetails
	3, // 4: SkuSrv.Create:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sku_proto_init() }
func file_sku_proto_init() {
	if File_sku_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sku_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkuDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sku_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkuDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sku_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSku); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sku_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sku_proto_goTypes,
		DependencyIndexes: file_sku_proto_depIdxs,
		MessageInfos:      file_sku_proto_msgTypes,
	}.Build()
	File_sku_proto = out.File
	file_sku_proto_rawDesc = nil
	file_sku_proto_goTypes = nil
	file_sku_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SkuSrvClient is the client API for SkuSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SkuSrvClient interface {
	GetAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SkuDetails, error)
	Create(ctx context.Context, in *CreateSku, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type skuSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewSkuSrvClient(cc grpc.ClientConnInterface) SkuSrvClient {
	return &skuSrvClient{cc}
}

func (c *skuSrvClient) GetAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SkuDetails, error) {
	out := new(SkuDetails)
	err := c.cc.Invoke(ctx, "/SkuSrv/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skuSrvClient) Create(ctx context.Context, in *CreateSku, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/SkuSrv/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkuSrvServer is the server API for SkuSrv service.
type SkuSrvServer interface {
	GetAll(context.Context, *emptypb.Empty) (*SkuDetails, error)
	Create(context.Context, *CreateSku) (*emptypb.Empty, error)
}

// UnimplementedSkuSrvServer can be embedded to have forward compatible implementations.
type UnimplementedSkuSrvServer struct {
}

func (*UnimplementedSkuSrvServer) GetAll(context.Context, *emptypb.Empty) (*SkuDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (*UnimplementedSkuSrvServer) Create(context.Context, *CreateSku) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterSkuSrvServer(s *grpc.Server, srv SkuSrvServer) {
	s.RegisterService(&_SkuSrv_serviceDesc, srv)
}

func _SkuSrv_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkuSrvServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SkuSrv/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkuSrvServer).GetAll(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkuSrv_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSku)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkuSrvServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SkuSrv/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkuSrvServer).Create(ctx, req.(*CreateSku))
	}
	return interceptor(ctx, in, info, handler)
}

var _SkuSrv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SkuSrv",
	HandlerType: (*SkuSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _SkuSrv_GetAll_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _SkuSrv_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sku.proto",
}
