// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: spec_param.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpecParamDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SpgId     int32  `protobuf:"varint,2,opt,name=spg_id,json=spgId,proto3" json:"spg_id,omitempty"`
	Name      string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Numeric   bool   `protobuf:"varint,5,opt,name=numeric,proto3" json:"numeric,omitempty"`
	Unit      string `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	Generic   bool   `protobuf:"varint,7,opt,name=generic,proto3" json:"generic,omitempty"`
	Searching bool   `protobuf:"varint,8,opt,name=searching,proto3" json:"searching,omitempty"`
	Segements string `protobuf:"bytes,9,opt,name=segements,proto3" json:"segements,omitempty"`
}

func (x *SpecParamDetail) Reset() {
	*x = SpecParamDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_param_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecParamDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecParamDetail) ProtoMessage() {}

func (x *SpecParamDetail) ProtoReflect() protoreflect.Message {
	mi := &file_spec_param_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecParamDetail.ProtoReflect.Descriptor instead.
func (*SpecParamDetail) Descriptor() ([]byte, []int) {
	return file_spec_param_proto_rawDescGZIP(), []int{0}
}

func (x *SpecParamDetail) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SpecParamDetail) GetSpgId() int32 {
	if x != nil {
		return x.SpgId
	}
	return 0
}

func (x *SpecParamDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpecParamDetail) GetNumeric() bool {
	if x != nil {
		return x.Numeric
	}
	return false
}

func (x *SpecParamDetail) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *SpecParamDetail) GetGeneric() bool {
	if x != nil {
		return x.Generic
	}
	return false
}

func (x *SpecParamDetail) GetSearching() bool {
	if x != nil {
		return x.Searching
	}
	return false
}

func (x *SpecParamDetail) GetSegements() string {
	if x != nil {
		return x.Segements
	}
	return ""
}

type SpecParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpecParam []*SpecParamDetail `protobuf:"bytes,1,rep,name=spec_param,json=specParam,proto3" json:"spec_param,omitempty"`
}

func (x *SpecParams) Reset() {
	*x = SpecParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_param_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecParams) ProtoMessage() {}

func (x *SpecParams) ProtoReflect() protoreflect.Message {
	mi := &file_spec_param_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecParams.ProtoReflect.Descriptor instead.
func (*SpecParams) Descriptor() ([]byte, []int) {
	return file_spec_param_proto_rawDescGZIP(), []int{1}
}

func (x *SpecParams) GetSpecParam() []*SpecParamDetail {
	if x != nil {
		return x.SpecParam
	}
	return nil
}

type CreateSpecParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpgId     int32  `protobuf:"varint,1,opt,name=spg_id,json=spgId,proto3" json:"spg_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Numeric   bool   `protobuf:"varint,3,opt,name=numeric,proto3" json:"numeric,omitempty"`
	Unit      string `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	Generic   bool   `protobuf:"varint,5,opt,name=generic,proto3" json:"generic,omitempty"`
	Searching bool   `protobuf:"varint,6,opt,name=searching,proto3" json:"searching,omitempty"`
	Segements string `protobuf:"bytes,7,opt,name=segements,proto3" json:"segements,omitempty"`
}

func (x *CreateSpecParam) Reset() {
	*x = CreateSpecParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_param_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSpecParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpecParam) ProtoMessage() {}

func (x *CreateSpecParam) ProtoReflect() protoreflect.Message {
	mi := &file_spec_param_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpecParam.ProtoReflect.Descriptor instead.
func (*CreateSpecParam) Descriptor() ([]byte, []int) {
	return file_spec_param_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSpecParam) GetSpgId() int32 {
	if x != nil {
		return x.SpgId
	}
	return 0
}

func (x *CreateSpecParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSpecParam) GetNumeric() bool {
	if x != nil {
		return x.Numeric
	}
	return false
}

func (x *CreateSpecParam) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *CreateSpecParam) GetGeneric() bool {
	if x != nil {
		return x.Generic
	}
	return false
}

func (x *CreateSpecParam) GetSearching() bool {
	if x != nil {
		return x.Searching
	}
	return false
}

func (x *CreateSpecParam) GetSegements() string {
	if x != nil {
		return x.Segements
	}
	return ""
}

var File_spec_param_proto protoreflect.FileDescriptor

var file_spec_param_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xd0, 0x01, 0x0a, 0x0f, 0x53, 0x70, 0x65, 0x63, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x70, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x70, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x69, 0x6e, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x67, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x22, 0x3d, 0x0a, 0x0a, 0x53, 0x70, 0x65, 0x63, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x12, 0x2f, 0x0a, 0x0a, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x09, 0x73, 0x70, 0x65, 0x63, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x22, 0xc0, 0x01, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x65, 0x63,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x70, 0x67, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x70, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e,
	0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x67, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x32, 0x75, 0x0a, 0x0c, 0x53, 0x70, 0x65, 0x63, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x53, 0x72, 0x76, 0x12, 0x2f, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0b, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12,
	0x10, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x65, 0x63, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spec_param_proto_rawDescOnce sync.Once
	file_spec_param_proto_rawDescData = file_spec_param_proto_rawDesc
)

func file_spec_param_proto_rawDescGZIP() []byte {
	file_spec_param_proto_rawDescOnce.Do(func() {
		file_spec_param_proto_rawDescData = protoimpl.X.CompressGZIP(file_spec_param_proto_rawDescData)
	})
	return file_spec_param_proto_rawDescData
}

var file_spec_param_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spec_param_proto_goTypes = []interface{}{
	(*SpecParamDetail)(nil), // 0: SpecParamDetail
	(*SpecParams)(nil),      // 1: SpecParams
	(*CreateSpecParam)(nil), // 2: CreateSpecParam
	(*emptypb.Empty)(nil),   // 3: google.protobuf.Empty
}
var file_spec_param_proto_depIdxs = []int32{
	0, // 0: SpecParams.spec_param:type_name -> SpecParamDetail
	3, // 1: SpecParamSrv.GetAll:input_type -> google.protobuf.Empty
	2, // 2: SpecParamSrv.Create:input_type -> CreateSpecParam
	1, // 3: SpecParamSrv.GetAll:output_type -> SpecParams
	3, // 4: SpecParamSrv.Create:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spec_param_proto_init() }
func file_spec_param_proto_init() {
	if File_spec_param_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spec_param_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecParamDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_param_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_param_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSpecParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spec_param_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spec_param_proto_goTypes,
		DependencyIndexes: file_spec_param_proto_depIdxs,
		MessageInfos:      file_spec_param_proto_msgTypes,
	}.Build()
	File_spec_param_proto = out.File
	file_spec_param_proto_rawDesc = nil
	file_spec_param_proto_goTypes = nil
	file_spec_param_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SpecParamSrvClient is the client API for SpecParamSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SpecParamSrvClient interface {
	GetAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SpecParams, error)
	Create(ctx context.Context, in *CreateSpecParam, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type specParamSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewSpecParamSrvClient(cc grpc.ClientConnInterface) SpecParamSrvClient {
	return &specParamSrvClient{cc}
}

func (c *specParamSrvClient) GetAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SpecParams, error) {
	out := new(SpecParams)
	err := c.cc.Invoke(ctx, "/SpecParamSrv/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specParamSrvClient) Create(ctx context.Context, in *CreateSpecParam, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/SpecParamSrv/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpecParamSrvServer is the server API for SpecParamSrv service.
type SpecParamSrvServer interface {
	GetAll(context.Context, *emptypb.Empty) (*SpecParams, error)
	Create(context.Context, *CreateSpecParam) (*emptypb.Empty, error)
}

// UnimplementedSpecParamSrvServer can be embedded to have forward compatible implementations.
type UnimplementedSpecParamSrvServer struct {
}

func (*UnimplementedSpecParamSrvServer) GetAll(context.Context, *emptypb.Empty) (*SpecParams, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (*UnimplementedSpecParamSrvServer) Create(context.Context, *CreateSpecParam) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterSpecParamSrvServer(s *grpc.Server, srv SpecParamSrvServer) {
	s.RegisterService(&_SpecParamSrv_serviceDesc, srv)
}

func _SpecParamSrv_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecParamSrvServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SpecParamSrv/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecParamSrvServer).GetAll(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecParamSrv_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSpecParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecParamSrvServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SpecParamSrv/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecParamSrvServer).Create(ctx, req.(*CreateSpecParam))
	}
	return interceptor(ctx, in, info, handler)
}

var _SpecParamSrv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SpecParamSrv",
	HandlerType: (*SpecParamSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _SpecParamSrv_GetAll_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _SpecParamSrv_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spec_param.proto",
}
