// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: spec_group.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpecGroupDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SpgId int32  `protobuf:"varint,2,opt,name=spg_id,json=spgId,proto3" json:"spg_id,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SpecGroupDetail) Reset() {
	*x = SpecGroupDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_group_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecGroupDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecGroupDetail) ProtoMessage() {}

func (x *SpecGroupDetail) ProtoReflect() protoreflect.Message {
	mi := &file_spec_group_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecGroupDetail.ProtoReflect.Descriptor instead.
func (*SpecGroupDetail) Descriptor() ([]byte, []int) {
	return file_spec_group_proto_rawDescGZIP(), []int{0}
}

func (x *SpecGroupDetail) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SpecGroupDetail) GetSpgId() int32 {
	if x != nil {
		return x.SpgId
	}
	return 0
}

func (x *SpecGroupDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SpecGroups struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpecGroup []*SpecGroupDetail `protobuf:"bytes,1,rep,name=spec_group,json=specGroup,proto3" json:"spec_group,omitempty"`
}

func (x *SpecGroups) Reset() {
	*x = SpecGroups{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_group_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecGroups) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecGroups) ProtoMessage() {}

func (x *SpecGroups) ProtoReflect() protoreflect.Message {
	mi := &file_spec_group_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecGroups.ProtoReflect.Descriptor instead.
func (*SpecGroups) Descriptor() ([]byte, []int) {
	return file_spec_group_proto_rawDescGZIP(), []int{1}
}

func (x *SpecGroups) GetSpecGroup() []*SpecGroupDetail {
	if x != nil {
		return x.SpecGroup
	}
	return nil
}

type CreateSpecGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpgId int32  `protobuf:"varint,1,opt,name=spg_id,json=spgId,proto3" json:"spg_id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateSpecGroup) Reset() {
	*x = CreateSpecGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_group_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSpecGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpecGroup) ProtoMessage() {}

func (x *CreateSpecGroup) ProtoReflect() protoreflect.Message {
	mi := &file_spec_group_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpecGroup.ProtoReflect.Descriptor instead.
func (*CreateSpecGroup) Descriptor() ([]byte, []int) {
	return file_spec_group_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSpecGroup) GetSpgId() int32 {
	if x != nil {
		return x.SpgId
	}
	return 0
}

func (x *CreateSpecGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_spec_group_proto protoreflect.FileDescriptor

var file_spec_group_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x4c, 0x0a, 0x0f, 0x53, 0x70, 0x65, 0x63, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x70, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x73, 0x70, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3d, 0x0a,
	0x0a, 0x53, 0x70, 0x65, 0x63, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x2f, 0x0a, 0x0a, 0x73,
	0x70, 0x65, 0x63, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x52, 0x09, 0x73, 0x70, 0x65, 0x63, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x3c, 0x0a, 0x0f,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x65, 0x63, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12,
	0x15, 0x0a, 0x06, 0x73, 0x70, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x73, 0x70, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x75, 0x0a, 0x0c, 0x53, 0x70,
	0x65, 0x63, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x72, 0x76, 0x12, 0x2f, 0x0a, 0x06, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0b, 0x2e, 0x53,
	0x70, 0x65, 0x63, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x06, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x10, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70,
	0x65, 0x63, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spec_group_proto_rawDescOnce sync.Once
	file_spec_group_proto_rawDescData = file_spec_group_proto_rawDesc
)

func file_spec_group_proto_rawDescGZIP() []byte {
	file_spec_group_proto_rawDescOnce.Do(func() {
		file_spec_group_proto_rawDescData = protoimpl.X.CompressGZIP(file_spec_group_proto_rawDescData)
	})
	return file_spec_group_proto_rawDescData
}

var file_spec_group_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spec_group_proto_goTypes = []interface{}{
	(*SpecGroupDetail)(nil), // 0: SpecGroupDetail
	(*SpecGroups)(nil),      // 1: SpecGroups
	(*CreateSpecGroup)(nil), // 2: CreateSpecGroup
	(*emptypb.Empty)(nil),   // 3: google.protobuf.Empty
}
var file_spec_group_proto_depIdxs = []int32{
	0, // 0: SpecGroups.spec_group:type_name -> SpecGroupDetail
	3, // 1: SpecGroupSrv.GetAll:input_type -> google.protobuf.Empty
	2, // 2: SpecGroupSrv.Create:input_type -> CreateSpecGroup
	1, // 3: SpecGroupSrv.GetAll:output_type -> SpecGroups
	3, // 4: SpecGroupSrv.Create:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spec_group_proto_init() }
func file_spec_group_proto_init() {
	if File_spec_group_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spec_group_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecGroupDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_group_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecGroups); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_group_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSpecGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spec_group_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spec_group_proto_goTypes,
		DependencyIndexes: file_spec_group_proto_depIdxs,
		MessageInfos:      file_spec_group_proto_msgTypes,
	}.Build()
	File_spec_group_proto = out.File
	file_spec_group_proto_rawDesc = nil
	file_spec_group_proto_goTypes = nil
	file_spec_group_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SpecGroupSrvClient is the client API for SpecGroupSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SpecGroupSrvClient interface {
	GetAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SpecGroups, error)
	Create(ctx context.Context, in *CreateSpecGroup, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type specGroupSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewSpecGroupSrvClient(cc grpc.ClientConnInterface) SpecGroupSrvClient {
	return &specGroupSrvClient{cc}
}

func (c *specGroupSrvClient) GetAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SpecGroups, error) {
	out := new(SpecGroups)
	err := c.cc.Invoke(ctx, "/SpecGroupSrv/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specGroupSrvClient) Create(ctx context.Context, in *CreateSpecGroup, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/SpecGroupSrv/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpecGroupSrvServer is the server API for SpecGroupSrv service.
type SpecGroupSrvServer interface {
	GetAll(context.Context, *emptypb.Empty) (*SpecGroups, error)
	Create(context.Context, *CreateSpecGroup) (*emptypb.Empty, error)
}

// UnimplementedSpecGroupSrvServer can be embedded to have forward compatible implementations.
type UnimplementedSpecGroupSrvServer struct {
}

func (*UnimplementedSpecGroupSrvServer) GetAll(context.Context, *emptypb.Empty) (*SpecGroups, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (*UnimplementedSpecGroupSrvServer) Create(context.Context, *CreateSpecGroup) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterSpecGroupSrvServer(s *grpc.Server, srv SpecGroupSrvServer) {
	s.RegisterService(&_SpecGroupSrv_serviceDesc, srv)
}

func _SpecGroupSrv_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecGroupSrvServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SpecGroupSrv/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecGroupSrvServer).GetAll(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecGroupSrv_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSpecGroup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecGroupSrvServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SpecGroupSrv/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecGroupSrvServer).Create(ctx, req.(*CreateSpecGroup))
	}
	return interceptor(ctx, in, info, handler)
}

var _SpecGroupSrv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SpecGroupSrv",
	HandlerType: (*SpecGroupSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _SpecGroupSrv_GetAll_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _SpecGroupSrv_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spec_group.proto",
}
